## Development environment
    
server:
    port: 8080

logging:
    level: DEBUG

spring:
    datasource:
        platform: h2
        url: jdbc:h2:~/compendium
        username: csa_admin
        password:

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        openInView: true
        show-sql: true
        generate-ddl: true
        hibernate:
            #ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy

