########################################################################################
######                 CSA Prioritization Tool - Configuration                    ######
######                    Carlos Ardila - CIAT/CCAFS - 2014                       ######
########################################################################################

# Disable the spring security default configuration from spring-boot-actuator
    
management:
    security:
        enabled: false
        context-path: /manage

security:
    basic:
        enabled: false

spring:
    profiles:
        active: dev
    datasource:
        initialize: true
        continueOnError: true