## Production environment

server:
    port: 8081
    
spring:
    datasource:
        platform: postgresql
        url: jdbc:postgresql://localhost:5432/compendium
        username: admin
        password: compendium

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        openInView: false
        show_sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
