## Production environment on Openshift

logging:
    level: DEBUG
    file: ${OPENSHIFT_DATA_DIR}/logs/app.log
    
spring:
    datasource:
        platform: postgresql
        jndi-name: jdbc/PostgreSQLDS
#        url: jdbc:postgresql://${OPENSHIFT_POSTGRESQL_DB_HOST}:${OPENSHIFT_POSTGRESQL_DB_PORT}/${OPENSHIFT_APP_NAME}
#        username: ${OPENSHIFT_POSTGRESQL_DB_USERNAME}
#        password: ${OPENSHIFT_POSTGRESQL_DB_PASSWORD}
#        platform: h2
#        url: jdbc:h2:${OPENSHIFT_DATA_DIR}/db/compendium;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#        username: csa_admin
#        password:

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        openInView: true
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy