## Production environment

server:
    port: 8088

spring:
    datasource:
        platform: mysql
        url: jdbc:mysql://localhost:3306/csa_compendium
        username: admin
        password: compendium

    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        openInView: false
        show_sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
