## Production environment on Openshift

logging:
    level: DEBUG
    file: ${OPENSHIFT_DATA_DIR}/logs/app.log
    
spring:
    datasource:
        platform: postgresql
        jndi-name: jdbc/PostgreSQLDS

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        openInView: true
        show_sql: true
        hibernate:
            ddl-auto: create-drop
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
