-- Initial data for the compendium

INSERT INTO themes VALUES (1, 'A', NULL, NULL, 'Agronomy');
INSERT INTO themes VALUES (2, 'B', NULL, NULL, 'Agroforestry');
INSERT INTO themes VALUES (3, 'C', NULL, NULL, 'Livestock');
INSERT INTO themes VALUES (4, 'D', NULL, NULL, 'Postharvest');
INSERT INTO themes VALUES (5, 'E', NULL, NULL, 'Food/Energy Systems');

-- 

INSERT INTO levels VALUES (1, '1', NULL, NULL, 'Intercropping', 2);
INSERT INTO levels VALUES (2, '2', NULL, NULL, 'Land restoration', 2);
INSERT INTO levels VALUES (3, '3', NULL, NULL, 'Parklands', 2);
INSERT INTO levels VALUES (4, '4', NULL, NULL, 'Boundary planting', 2);
INSERT INTO levels VALUES (5, '5', NULL, NULL, 'Silvopasture', 2);
INSERT INTO levels VALUES (6, '6', NULL, NULL, 'Multi-strata agroforestry', 2);

--

INSERT INTO context_variables VALUES (1, 'TA', 'Description of source that contains the data', NULL, 'Type of Article', 'EXPERIMENT');
INSERT INTO context_variables VALUES (2, 'TS', 'Description of the nature of the conducted study or experiment', NULL, 'Type of Study', 'EXPERIMENT');

INSERT INTO context_values VALUES (1, '1', 'An article published on a peer-reviewd publication', NULL, 'Peer Reviewed Article', 1);
INSERT INTO context_values VALUES (2, '2', 'A publicly available report on project results', NULL, 'Report', 1);
INSERT INTO context_values VALUES (3, '3', 'Documents from Doctoral/Master/Undergraduate Thesis', NULL, 'Thesis/Dissertation', 1);
INSERT INTO context_values VALUES (4, '4', 'Data collected on internal unpublished document', NULL, 'Unpublished Data', 1);
INSERT INTO context_values VALUES (5, '5', 'An internal unpublished document from a project', NULL, 'Working Paper', 1);
INSERT INTO context_values VALUES (6, '6', 'Chapter of apublished book', NULL, 'Book Chapter', 1);

INSERT INTO context_values VALUES (7, '1', NULL, NULL, 'Farmers field', 2);
INSERT INTO context_values VALUES (8, '2', NULL, NULL, 'Experimental field', 2);
INSERT INTO context_values VALUES (9, '3', NULL, NULL, 'Modeling', 2);
INSERT INTO context_values VALUES (10, '4', NULL, NULL, 'Greenhouse/Lab/pot', 2);
INSERT INTO context_values VALUES (11, '5', 'A study that can not be categorized under the existing categories', NULL, 'Other', 2);
INSERT INTO context_values VALUES (12, '6', 'A survey conducted in a farm of farmers home', NULL, 'Household survey', 2);
INSERT INTO context_values VALUES (13, '7', 'A combination of previews items', NULL, 'Combination 1-6', 2);
INSERT INTO context_values VALUES (14, '8', 'Interviews and semistructured questionnaires', NULL, 'Interview', 2);
INSERT INTO context_values VALUES (15, '9', 'Focus Groups, Community Activties', NULL, 'PRAs', 2);

--

INSERT INTO languages VALUES ('1', 'English', 'English');
INSERT INTO languages VALUES ('2', 'Spanish', 'Español');
INSERT INTO languages VALUES ('3', 'French', 'Françoise');
INSERT INTO languages VALUES ('4', 'Portuguese', 'Português');
INSERT INTO languages VALUES ('5', 'Chinese', '中国');

INSERT INTO regions VALUES ('AFR', 'Sub-Saharan Africa');
INSERT INTO regions VALUES ('MNA', 'Middle East and North Africa');
INSERT INTO regions VALUES ('ECA', 'Eastern Europe and Central Asia (West, Central)');
INSERT INTO regions VALUES ('SAS', 'South Asia');
INSERT INTO regions VALUES ('EAP', 'East Asia and Pacific');
INSERT INTO regions VALUES ('LAC', 'Latin America and Caribbean');

INSERT INTO farming_systems VALUES (1, 'a1', NULL, NULL, 'Irrigated', 'AFR');
INSERT INTO farming_systems VALUES (2, 'a2', NULL, NULL, 'Tree crop', 'AFR');
INSERT INTO farming_systems VALUES (3, 'a3', NULL, NULL, 'Forest based', 'AFR');
INSERT INTO farming_systems VALUES (4, 'a4', NULL, NULL, 'Rice-tree crop', 'AFR');
INSERT INTO farming_systems VALUES (5, 'a5', NULL, NULL, 'Highland perennial', 'AFR');
INSERT INTO farming_systems VALUES (6, 'a6', NULL, NULL, 'Highland temperate mixed', 'AFR');
INSERT INTO farming_systems VALUES (7, 'a7', NULL, NULL, 'Root crop', 'AFR');
INSERT INTO farming_systems VALUES (8, 'a8', NULL, NULL, 'Cereal-root crop mixed', 'AFR');
INSERT INTO farming_systems VALUES (9, 'a9', NULL, NULL, 'Maize mixed', 'AFR');
INSERT INTO farming_systems VALUES (10, 'a10', NULL, NULL, 'Large commercial & smallholder', 'AFR');
INSERT INTO farming_systems VALUES (11, 'a11', NULL, NULL, 'Agro-pastoral millet/sorghum', 'AFR');
INSERT INTO farming_systems VALUES (12, 'a12', NULL, NULL, 'Pastoral', 'AFR');
INSERT INTO farming_systems VALUES (13, 'a13', NULL, NULL, 'Sparse (arid)', 'AFR');
INSERT INTO farming_systems VALUES (14, 'a14', NULL, NULL, 'Coastal artisanal fishing', 'AFR');
INSERT INTO farming_systems VALUES (15, 'a15', NULL, NULL, 'Urban based (not mapped)', 'AFR');
INSERT INTO farming_systems VALUES (16, 'b1', NULL, NULL, 'Irrigated', 'MNA');
INSERT INTO farming_systems VALUES (17, 'b2', NULL, NULL, 'Highland mixed', 'MNA');
INSERT INTO farming_systems VALUES (18, 'b3', NULL, NULL, 'Rainfed mixed', 'MNA');
INSERT INTO farming_systems VALUES (19, 'b4', NULL, NULL, 'Dryland mixed', 'MNA');
INSERT INTO farming_systems VALUES (20, 'b5', NULL, NULL, 'Pastoral', 'MNA');
INSERT INTO farming_systems VALUES (21, 'b6', NULL, NULL, 'Sparse (arid)', 'MNA');
INSERT INTO farming_systems VALUES (22, 'b7', NULL, NULL, 'Coastal artisanal fishing (not mapped)', 'MNA');
INSERT INTO farming_systems VALUES (23, 'b8', NULL, NULL, 'Urban based (not mapped)', 'MNA');
INSERT INTO farming_systems VALUES (24, 'c1', NULL, NULL, 'Irrigated', 'ECA');
INSERT INTO farming_systems VALUES (25, 'c2', NULL, NULL, 'Mixed', 'ECA');
INSERT INTO farming_systems VALUES (26, 'c3', NULL, NULL, 'Forest based livestock', 'ECA');
INSERT INTO farming_systems VALUES (27, 'c4', NULL, NULL, 'Horticulture mixed', 'ECA');
INSERT INTO farming_systems VALUES (28, 'c5', NULL, NULL, 'Large scale cereal-vegetable', 'ECA');
INSERT INTO farming_systems VALUES (29, 'c6', NULL, NULL, 'Small scale cereal-livestock', 'ECA');
INSERT INTO farming_systems VALUES (30, 'c7', NULL, NULL, 'Extensive cereal-livestock', 'ECA');
INSERT INTO farming_systems VALUES (31, 'c8', NULL, NULL, 'Pastoral', 'ECA');
INSERT INTO farming_systems VALUES (32, 'c9', NULL, NULL, 'Sparse (cold)', 'ECA');
INSERT INTO farming_systems VALUES (33, 'c10', NULL, NULL, 'Sparse (arid)', 'ECA');
INSERT INTO farming_systems VALUES (34, 'c11', NULL, NULL, 'Urban based (not mapped)', 'ECA');
INSERT INTO farming_systems VALUES (35, 'd1', NULL, NULL, 'Rice', 'SAS');
INSERT INTO farming_systems VALUES (36, 'd2', NULL, NULL, 'Coastal artisanal fishing', 'SAS');
INSERT INTO farming_systems VALUES (37, 'd3', NULL, NULL, 'Rice-wheat', 'SAS');
INSERT INTO farming_systems VALUES (38, 'd4', NULL, NULL, 'Highland mixed', 'SAS');
INSERT INTO farming_systems VALUES (39, 'd5', NULL, NULL, 'Rainfed mixed', 'SAS');
INSERT INTO farming_systems VALUES (40, 'd6', NULL, NULL, 'Dry rainfed', 'SAS');
INSERT INTO farming_systems VALUES (41, 'd7', NULL, NULL, 'Pastoral', 'SAS');
INSERT INTO farming_systems VALUES (42, 'd8', NULL, NULL, 'Sparse (arid)', 'SAS');
INSERT INTO farming_systems VALUES (43, 'd9', NULL, NULL, 'Sparse (mountain)', 'SAS');
INSERT INTO farming_systems VALUES (44, 'd10', NULL, NULL, 'Tree crop (not mapped)', 'SAS');
INSERT INTO farming_systems VALUES (45, 'd11', NULL, NULL, 'Urban based (not mapped)', 'SAS');
INSERT INTO farming_systems VALUES (46, 'e1', NULL, NULL, 'Lowland rice', 'EAP');
INSERT INTO farming_systems VALUES (47, 'e2', NULL, NULL, 'Tree crop mixed', 'EAP');
INSERT INTO farming_systems VALUES (48, 'e3', NULL, NULL, 'Root-tuber', 'EAP');
INSERT INTO farming_systems VALUES (49, 'e4', NULL, NULL, 'Upland intensive mixed', 'EAP');
INSERT INTO farming_systems VALUES (50, 'e5', NULL, NULL, 'Highland extensive mixed', 'EAP');
INSERT INTO farming_systems VALUES (51, 'e6', NULL, NULL, 'Temperate mixed', 'EAP');
INSERT INTO farming_systems VALUES (52, 'e7', NULL, NULL, 'Pastoral', 'EAP');
INSERT INTO farming_systems VALUES (53, 'e8', NULL, NULL, 'Sparse (forest)', 'EAP');
INSERT INTO farming_systems VALUES (54, 'e9', NULL, NULL, 'Sparse (arid)', 'EAP');
INSERT INTO farming_systems VALUES (55, 'e10', NULL, NULL, 'Coastal artisanal fishing (not mapped)', 'EAP');
INSERT INTO farming_systems VALUES (56, 'e11', NULL, NULL, 'Urban based (not mapped)', 'EAP');
INSERT INTO farming_systems VALUES (57, 'f1', NULL, NULL, 'Irrigated', 'LAC');
INSERT INTO farming_systems VALUES (58, 'f2', NULL, NULL, 'Forest based', 'LAC');
INSERT INTO farming_systems VALUES (59, 'f3', NULL, NULL, 'Coastal plantation & mixed', 'LAC');
INSERT INTO farming_systems VALUES (60, 'f4', NULL, NULL, 'Intensive mixed', 'LAC');
INSERT INTO farming_systems VALUES (61, 'f5', NULL, NULL, 'Cereal-livestock (Campos)', 'LAC');
INSERT INTO farming_systems VALUES (62, 'f6', NULL, NULL, 'Maize-beans (Mesoamerica)', 'LAC');
INSERT INTO farming_systems VALUES (63, 'f7', NULL, NULL, 'Extensive mixed (Cerrados & Llanos)', 'LAC');
INSERT INTO farming_systems VALUES (64, 'f8', NULL, NULL, 'Intensive highland mixed (North Andes)', 'LAC');
INSERT INTO farming_systems VALUES (65, 'f9', NULL, NULL, 'High altitude mixed (Central Andes)', 'LAC');
INSERT INTO farming_systems VALUES (66, 'f10', NULL, NULL, 'Mediterranean mixed', 'LAC');
INSERT INTO farming_systems VALUES (67, 'f11', NULL, NULL, 'Temperate mixed (Pampas)', 'LAC');
INSERT INTO farming_systems VALUES (68, 'f12', NULL, NULL, 'Extensive dryland mixed (Gran Chaco)', 'LAC');
INSERT INTO farming_systems VALUES (69, 'f13', NULL, NULL, 'Dryland mixed', 'LAC');
INSERT INTO farming_systems VALUES (70, 'f14', NULL, NULL, 'Pastoral', 'LAC');
INSERT INTO farming_systems VALUES (71, 'f15', NULL, NULL, 'Sparse (forest)', 'LAC');
INSERT INTO farming_systems VALUES (72, 'f16', NULL, NULL, 'Urban based (not mapped)', 'LAC');
INSERT INTO farming_systems VALUES (73, 'f17', NULL, NULL, 'Moist temperate mixed-forest', 'LAC');

-- countries



--

INSERT INTO categories VALUES (1, 'A', 'Livestock', NULL, 'Animals');
INSERT INTO categories VALUES (2, 'B', NULL, NULL, 'Berries');
INSERT INTO categories VALUES (3, 'C', NULL, NULL, 'Cereals');
INSERT INTO categories VALUES (4, 'D', NULL, NULL, 'Fibre crops');
INSERT INTO categories VALUES (5, 'E', NULL, NULL, 'Fruits');
INSERT INTO categories VALUES (6, 'F', NULL, NULL, 'Nuts, seeds');
INSERT INTO categories VALUES (7, 'G', NULL, NULL, 'Oil crops');
INSERT INTO categories VALUES (8, 'H', NULL, NULL, 'Pulses');
INSERT INTO categories VALUES (9, 'I', NULL, NULL, 'Roots, tubers');
INSERT INTO categories VALUES (10, 'J', NULL, NULL, 'Spices');
INSERT INTO categories VALUES (11, 'K', NULL, NULL, 'Vegetables');
INSERT INTO categories VALUES (12, 'L', NULL, NULL, 'Other plant products');
INSERT INTO categories VALUES (13, 'M', NULL, NULL, 'FES');
INSERT INTO categories VALUES (14, 'N', NULL, NULL, 'Other');
INSERT INTO categories VALUES (15, 'O', NULL, NULL, 'Forage');
INSERT INTO categories VALUES (16, 'P', NULL, NULL, 'Post-harvest');
INSERT INTO categories VALUES (17, 'Q', NULL, NULL, 'Residues');
INSERT INTO categories VALUES (18, 'R', NULL, NULL, 'Trees');
INSERT INTO categories VALUES (19, 'S', NULL, NULL, 'Cover crops/green manures');

INSERT INTO production_systems VALUES (1, 'a1', '', NULL, 'Animals (general/other)', 1);
INSERT INTO production_systems VALUES (2, 'a2', '', NULL, 'Bees', 1);
INSERT INTO production_systems VALUES (3, 'a3', '', NULL, 'Beeswax', 1);
INSERT INTO production_systems VALUES (4, 'a4', '', NULL, 'Birds', 1);
INSERT INTO production_systems VALUES (5, 'a5', '', NULL, 'Buffalo', 1);
INSERT INTO production_systems VALUES (6, 'a6', '', NULL, 'Camel', 1);
INSERT INTO production_systems VALUES (7, 'a7', '', NULL, 'Chicken', 1);
INSERT INTO production_systems VALUES (8, 'a8', '', NULL, 'Cattle', 1);
INSERT INTO production_systems VALUES (9, 'a23', '', NULL, 'Crustaceans', 1);
INSERT INTO production_systems VALUES (10, 'a9', '', NULL, 'Duck', 1);
INSERT INTO production_systems VALUES (11, 'a26', '', NULL, 'Draught power', 1);
INSERT INTO production_systems VALUES (12, 'a10', '', NULL, 'Eggs, hen', 1);
INSERT INTO production_systems VALUES (13, 'a11', '', NULL, 'Eggs, other bird', 1);
INSERT INTO production_systems VALUES (14, 'a28', '', NULL, 'Feathers', 1);
INSERT INTO production_systems VALUES (15, 'a29', '', NULL, 'Fingerlings', 1);
INSERT INTO production_systems VALUES (16, 'a24', '', NULL, 'Fish', 1);
INSERT INTO production_systems VALUES (17, 'a12', '', NULL, 'Geese', 1);
INSERT INTO production_systems VALUES (18, 'a13', '', NULL, 'Goat', 1);
INSERT INTO production_systems VALUES (19, 'a30', '', NULL, 'Hatchlings', 1);
INSERT INTO production_systems VALUES (20, 'a31', '', NULL, 'Hides', 1);
INSERT INTO production_systems VALUES (21, 'a14', '', NULL, 'Horse', 1);
INSERT INTO production_systems VALUES (22, 'a32', '', NULL, 'Meat', 1);
INSERT INTO production_systems VALUES (23, 'a33', '', NULL, 'Milk', 1);
INSERT INTO production_systems VALUES (24, 'a25', '', NULL, 'Mollusc', 1);
INSERT INTO production_systems VALUES (25, 'a15', '', NULL, 'Mule', 1);
INSERT INTO production_systems VALUES (26, 'a16', '', NULL, 'Pig', 1);
INSERT INTO production_systems VALUES (27, 'a17', '', NULL, 'Pigeons, other birds', 1);
INSERT INTO production_systems VALUES (28, 'a18', '', NULL, 'Rabbit', 1);
INSERT INTO production_systems VALUES (29, 'a19', '', NULL, 'Rodents', 1);
INSERT INTO production_systems VALUES (30, 'a34', '', NULL, 'Semen', 1);
INSERT INTO production_systems VALUES (31, 'a20', '', NULL, 'Sheep', 1);
INSERT INTO production_systems VALUES (32, 'a35', '', NULL, 'Skins', 1);
INSERT INTO production_systems VALUES (33, 'a21', '', NULL, 'Snails', 1);
INSERT INTO production_systems VALUES (34, 'a22', '', NULL, 'Turkey', 1);
INSERT INTO production_systems VALUES (35, 'a36', '', NULL, 'Wool', 1);
INSERT INTO production_systems VALUES (36, 'b1', '', NULL, 'Berries (general/other)', 2);
INSERT INTO production_systems VALUES (37, 'b2', '', NULL, 'Blueberries', 2);
INSERT INTO production_systems VALUES (38, 'b3', '', NULL, 'Cherries', 2);
INSERT INTO production_systems VALUES (39, 'b4', '', NULL, 'Cranberries', 2);
INSERT INTO production_systems VALUES (40, 'b5', '', NULL, 'Currants', 2);
INSERT INTO production_systems VALUES (41, 'b6', '', NULL, 'Gooseberries', 2);
INSERT INTO production_systems VALUES (42, 'b7', '', NULL, 'Raspberries', 2);
INSERT INTO production_systems VALUES (43, 'b8', '', NULL, 'Strawberries', 2);
INSERT INTO production_systems VALUES (44, 'c1', '', NULL, 'Cereals (general/other)', 3);
INSERT INTO production_systems VALUES (45, 'c2', '', NULL, 'Amaranth', 3);
INSERT INTO production_systems VALUES (46, 'c3', '', NULL, 'Barley', 3);
INSERT INTO production_systems VALUES (47, 'c4', '', NULL, 'Buckwheat', 3);
INSERT INTO production_systems VALUES (48, 'c5', '', NULL, 'Canary seed Carobs', 3);
INSERT INTO production_systems VALUES (49, 'c6', '', NULL, 'Fonio', 3);
INSERT INTO production_systems VALUES (50, 'c7', '', NULL, 'Maize', 3);
INSERT INTO production_systems VALUES (51, 'c8', '', NULL, 'Millet', 3);
INSERT INTO production_systems VALUES (52, 'c9', '', NULL, 'Oats', 3);
INSERT INTO production_systems VALUES (53, 'c10', '', NULL, 'Quinoa', 3);
INSERT INTO production_systems VALUES (54, 'c11', '', NULL, 'Rice', 3);
INSERT INTO production_systems VALUES (55, 'c12', '', NULL, 'Rye', 3);
INSERT INTO production_systems VALUES (56, 'c13', '', NULL, 'Sorghum', 3);
INSERT INTO production_systems VALUES (57, 'c14', '', NULL, 'Wheat', 3);
INSERT INTO production_systems VALUES (58, 'c15', '', NULL, 'Tef', 3);
INSERT INTO production_systems VALUES (59, 'c16', '', NULL, 'Finger millet', 3);
INSERT INTO production_systems VALUES (60, 'c17', '', NULL, 'Pearl millet', 3);
INSERT INTO production_systems VALUES (61, 'd1', '', NULL, 'Fibre crops (general/other)', 4);
INSERT INTO production_systems VALUES (62, 'd2', '', NULL, 'Agave fibres', 4);
INSERT INTO production_systems VALUES (63, 'd3', '', NULL, 'Bastfibres, other', 4);
INSERT INTO production_systems VALUES (64, 'd4', '', NULL, 'Coir', 4);
INSERT INTO production_systems VALUES (65, 'd5', '', NULL, 'Cotton', 4);
INSERT INTO production_systems VALUES (66, 'd6', '', NULL, 'Flax fibre and tow', 4);
INSERT INTO production_systems VALUES (67, 'd7', '', NULL, 'Hemp', 4);
INSERT INTO production_systems VALUES (68, 'd8', '', NULL, 'Jute', 4);
INSERT INTO production_systems VALUES (69, 'd9', '', NULL, 'Kapok', 4);
INSERT INTO production_systems VALUES (70, 'd10', '', NULL, 'Manila fibre (abaca)', 4);
INSERT INTO production_systems VALUES (71, 'd11', '', NULL, 'Ramie', 4);
INSERT INTO production_systems VALUES (72, 'd12', '', NULL, 'Seed cotton', 4);
INSERT INTO production_systems VALUES (73, 'd13', '', NULL, 'Silk-worm cocoons', 4);
INSERT INTO production_systems VALUES (74, 'd14', '', NULL, 'Sisal', 4);
INSERT INTO production_systems VALUES (75, 'd15', '', NULL, 'Roselle (Hibiscus)', 4);
INSERT INTO production_systems VALUES (76, 'e1', '', NULL, 'Apples', 5);
INSERT INTO production_systems VALUES (77, 'e2', '', NULL, 'Apricots', 5);
INSERT INTO production_systems VALUES (78, 'e3', '', NULL, 'Avocados', 5);
INSERT INTO production_systems VALUES (79, 'e4', '', NULL, 'Bananas', 5);
INSERT INTO production_systems VALUES (80, 'e5', '', NULL, 'Cashew apple', 5);
INSERT INTO production_systems VALUES (81, 'e6', '', NULL, 'Figs', 5);
INSERT INTO production_systems VALUES (82, 'e7', '', NULL, 'Fruit, citrus (general/other)', 5);
INSERT INTO production_systems VALUES (83, 'e8', '', NULL, 'Fruit (general/other)', 5);
INSERT INTO production_systems VALUES (84, 'e9', '', NULL, 'Fruit, pome (general/other)', 5);
INSERT INTO production_systems VALUES (85, 'e10', '', NULL, 'Grapefruit (inc. pomelos)', 5);
INSERT INTO production_systems VALUES (86, 'e11', '', NULL, 'Grapes', 5);
INSERT INTO production_systems VALUES (87, 'e12', '', NULL, 'Kiwi fruit', 5);
INSERT INTO production_systems VALUES (88, 'e13', '', NULL, 'Lemons and limes', 5);
INSERT INTO production_systems VALUES (89, 'e14', '', NULL, 'Mangoes, mangosteens, guavas', 5);
INSERT INTO production_systems VALUES (90, 'e15', '', NULL, 'Melons, other (inc.cantaloupes)', 5);
INSERT INTO production_systems VALUES (91, 'e16', '', NULL, 'Nectarines', 5);
INSERT INTO production_systems VALUES (92, 'e17', '', NULL, 'Oranges', 5);
INSERT INTO production_systems VALUES (93, 'e18', '', NULL, 'Papayas', 5);
INSERT INTO production_systems VALUES (94, 'e19', '', NULL, 'Peach', 5);
INSERT INTO production_systems VALUES (95, 'e20', '', NULL, 'Pears', 5);
INSERT INTO production_systems VALUES (96, 'e21', '', NULL, 'Persimmons', 5);
INSERT INTO production_systems VALUES (97, 'e22', '', NULL, 'Pineapples', 5);
INSERT INTO production_systems VALUES (98, 'e23', '', NULL, 'Plantains', 5);
INSERT INTO production_systems VALUES (99, 'e24', '', NULL, 'Plums and sloes', 5);
INSERT INTO production_systems VALUES (100, 'e25', '', NULL, 'Quinces', 5);
INSERT INTO production_systems VALUES (101, 'e26', '', NULL, 'Tangerines, mandarins, clementines, satsumas', 5);
INSERT INTO production_systems VALUES (102, 'e27', '', NULL, 'Tomatoes', 5);
INSERT INTO production_systems VALUES (103, 'e28', '', NULL, 'Watermelons', 5);
INSERT INTO production_systems VALUES (104, 'e29', '', NULL, 'Yellow Passion fruit', 5);
INSERT INTO production_systems VALUES (105, 'e30', '', NULL, 'Fruit trees (general)', 5);
INSERT INTO production_systems VALUES (106, 'e31', '', NULL, 'Musklmelon', 5);
INSERT INTO production_systems VALUES (107, 'e32', '', NULL, 'Pomegranate', 5);
INSERT INTO production_systems VALUES (108, 'e33', '', NULL, 'Sapota', 5);
INSERT INTO production_systems VALUES (109, 'e34', '', NULL, 'Peach-palm', 5);
INSERT INTO production_systems VALUES (110, 'e35', '', NULL, 'Ber/Chinee Apple/Jujube/Indian plum/Masau', 5);
INSERT INTO production_systems VALUES (111, 'e37', '', NULL, 'Cherry tree', 5);
INSERT INTO production_systems VALUES (112, 'f1', '', NULL, 'Nuts, seeds (general/other)', 6);
INSERT INTO production_systems VALUES (113, 'f2', '', NULL, 'Almonds', 6);
INSERT INTO production_systems VALUES (114, 'f3', '', NULL, 'Areca nuts', 6);
INSERT INTO production_systems VALUES (115, 'f4', '', NULL, 'Brazil nuts', 6);
INSERT INTO production_systems VALUES (116, 'f5', '', NULL, 'Cashew nuts', 6);
INSERT INTO production_systems VALUES (117, 'f6', '', NULL, 'Chestnut', 6);
INSERT INTO production_systems VALUES (118, 'f7', '', NULL, 'Hazelnuts', 6);
INSERT INTO production_systems VALUES (119, 'f8', '', NULL, 'Karite nuts (sheanuts)', 6);
INSERT INTO production_systems VALUES (120, 'f9', '', NULL, 'Kola nuts', 6);
INSERT INTO production_systems VALUES (121, 'f10', '', NULL, 'Linseed', 6);
INSERT INTO production_systems VALUES (122, 'f11', '', NULL, 'Melonseed', 6);
INSERT INTO production_systems VALUES (123, 'f12', '', NULL, 'Mustard seed', 6);
INSERT INTO production_systems VALUES (124, 'f13', '', NULL, 'Pistachios', 6);
INSERT INTO production_systems VALUES (125, 'f14', '', NULL, 'Pyrethrum', 6);
INSERT INTO production_systems VALUES (126, 'f15', '', NULL, 'Safflower seed', 6);
INSERT INTO production_systems VALUES (127, 'f16', '', NULL, 'Sesame seed', 6);
INSERT INTO production_systems VALUES (128, 'f17', '', NULL, 'Triticale Tung nuts', 6);
INSERT INTO production_systems VALUES (129, 'f18', '', NULL, 'Walnuts', 6);
INSERT INTO production_systems VALUES (130, 'f19', '', NULL, 'Seeds (general/other)', 6);
INSERT INTO production_systems VALUES (131, 'f20', '', NULL, 'Peanut', 6);
INSERT INTO production_systems VALUES (132, 'g1', '', NULL, 'Oilseeds (general/other)', 7);
INSERT INTO production_systems VALUES (133, 'g2', '', NULL, 'Castor oil seed', 7);
INSERT INTO production_systems VALUES (134, 'g3', '', NULL, 'Jojoba seed', 7);
INSERT INTO production_systems VALUES (135, 'g4', '', NULL, 'Oil, palm', 7);
INSERT INTO production_systems VALUES (136, 'g5', '', NULL, 'Oil, palm fruit', 7);
INSERT INTO production_systems VALUES (137, 'g6', '', NULL, 'Olives', 7);
INSERT INTO production_systems VALUES (138, 'g7', '', NULL, 'Palm kernels', 7);
INSERT INTO production_systems VALUES (139, 'g8', '', NULL, 'Rapeseed', 7);
INSERT INTO production_systems VALUES (140, 'g9', '', NULL, 'Sunflower seed', 7);
INSERT INTO production_systems VALUES (141, 'g10', '', NULL, 'Tallow tree seed', 7);
INSERT INTO production_systems VALUES (142, 'g11', '', NULL, 'Jatropha', 7);
INSERT INTO production_systems VALUES (143, 'g12', '', NULL, 'Niger', 7);
INSERT INTO production_systems VALUES (144, 'h1', '', NULL, 'Pulses (general/other)', 8);
INSERT INTO production_systems VALUES (145, 'h2', '', NULL, 'Beans (general/other)', 8);
INSERT INTO production_systems VALUES (146, 'h3', '', NULL, 'Mung beans/green grams', 8);
INSERT INTO production_systems VALUES (147, 'h4', '', NULL, 'Peas (general/other)', 8);
INSERT INTO production_systems VALUES (148, 'h5', '', NULL, 'Bambara beans', 8);
INSERT INTO production_systems VALUES (149, 'h6', '', NULL, 'Broad beans, horse beans', 8);
INSERT INTO production_systems VALUES (150, 'h7', '', NULL, 'Chick peas', 8);
INSERT INTO production_systems VALUES (151, 'h8', '', NULL, 'Cow peas, cowpea', 8);
INSERT INTO production_systems VALUES (152, 'h9', '', NULL, 'Groundnuts/Peanut', 8);
INSERT INTO production_systems VALUES (153, 'h10', '', NULL, 'Lentils', 8);
INSERT INTO production_systems VALUES (154, 'h11', '', NULL, 'Lupins', 8);
INSERT INTO production_systems VALUES (155, 'h12', '', NULL, 'Pigeon peas', 8);
INSERT INTO production_systems VALUES (156, 'h13', '', NULL, 'Soybeans', 8);
INSERT INTO production_systems VALUES (157, 'h14', '', NULL, 'String bean/french bean/green bean/common bean/haricot field bean', 8);
INSERT INTO production_systems VALUES (158, 'h15', '', NULL, 'Vetches', 8);
INSERT INTO production_systems VALUES (159, 'h16', '', NULL, 'Cluster bean', 8);
INSERT INTO production_systems VALUES (160, 'h17', '', NULL, 'Long bean/pea bean/snake bean', 8);
INSERT INTO production_systems VALUES (161, 'h18', '', NULL, 'Rice bean', 8);
INSERT INTO production_systems VALUES (162, 'h19', '', NULL, 'Horsegram', 8);
INSERT INTO production_systems VALUES (163, 'h20', '', NULL, 'faba beans', 8);
INSERT INTO production_systems VALUES (164, 'h21', '', NULL, 'black gram', 8);
INSERT INTO production_systems VALUES (165, 'i2', '', NULL, 'Carrots and turnips', 9);
INSERT INTO production_systems VALUES (166, 'i3', '', NULL, 'Cassava', 9);
INSERT INTO production_systems VALUES (167, 'i4', '', NULL, 'Chicory roots', 9);
INSERT INTO production_systems VALUES (168, 'i5', '', NULL, 'Garlic', 9);
INSERT INTO production_systems VALUES (169, 'i6', '', NULL, 'Ginger', 9);
INSERT INTO production_systems VALUES (170, 'i7', '', NULL, 'Potatoes', 9);
INSERT INTO production_systems VALUES (171, 'i8', '', NULL, 'Sugar beet', 9);
INSERT INTO production_systems VALUES (172, 'i9', '', NULL, 'Sweet potatoes', 9);
INSERT INTO production_systems VALUES (173, 'i10', '', NULL, 'Taro/Yautia (cocoyam)', 9);
INSERT INTO production_systems VALUES (174, 'i11', '', NULL, 'Yams', 9);
INSERT INTO production_systems VALUES (175, 'i12', '', NULL, 'Yautia (cocoyam)', 9);
INSERT INTO production_systems VALUES (176, 'i13', '', NULL, 'Turmeric', 9);
INSERT INTO production_systems VALUES (177, 'i14', '', NULL, 'Colocasia', 9);
INSERT INTO production_systems VALUES (178, 'j1', '', NULL, 'Spices (general/other)', 10);
INSERT INTO production_systems VALUES (179, 'j2', '', NULL, 'Anise, badian, fennel, coriander', 10);
INSERT INTO production_systems VALUES (180, 'j3', '', NULL, 'Cardamoms', 10);
INSERT INTO production_systems VALUES (181, 'j4', '', NULL, 'Chillies and peppers', 10);
INSERT INTO production_systems VALUES (182, 'j5', '', NULL, 'Cinnamon (canella)', 10);
INSERT INTO production_systems VALUES (183, 'j6', '', NULL, 'Cloves', 10);
INSERT INTO production_systems VALUES (184, 'j7', '', NULL, 'Nutmeg, mace', 10);
INSERT INTO production_systems VALUES (185, 'j8', '', NULL, 'Pepper (piper spp.)', 10);
INSERT INTO production_systems VALUES (186, 'j9', '', NULL, 'Peppermint', 10);
INSERT INTO production_systems VALUES (187, 'j10', '', NULL, 'Vanilla', 10);
INSERT INTO production_systems VALUES (188, 'j11', '', NULL, 'Cumin', 10);
INSERT INTO production_systems VALUES (189, 'k1', '', NULL, 'Vegetables (general/other)', 11);
INSERT INTO production_systems VALUES (190, 'k2', '', NULL, 'Vegetables, leguminous (general/other)', 11);
INSERT INTO production_systems VALUES (191, 'k3', '', NULL, 'Vegetables, leafy (general/other)', 11);
INSERT INTO production_systems VALUES (192, 'k4', '', NULL, 'Artichokes', 11);
INSERT INTO production_systems VALUES (193, 'k5', '', NULL, 'Asparagus', 11);
INSERT INTO production_systems VALUES (194, 'k6', '', NULL, 'Cabbages and other brassicas', 11);
INSERT INTO production_systems VALUES (195, 'k7', '', NULL, 'Cauliflower and broccoli', 11);
INSERT INTO production_systems VALUES (196, 'k8', '', NULL, 'Cucumbers and gherkins', 11);
INSERT INTO production_systems VALUES (197, 'k9', '', NULL, 'Leeks, other alliaceous vegetables', 11);
INSERT INTO production_systems VALUES (198, 'k10', '', NULL, 'Lettuce and chicory', 11);
INSERT INTO production_systems VALUES (199, 'k11', '', NULL, 'Okra', 11);
INSERT INTO production_systems VALUES (200, 'k12', '', NULL, 'Onions', 11);
INSERT INTO production_systems VALUES (201, 'k13', '', NULL, 'Onions, shallots, green', 11);
INSERT INTO production_systems VALUES (202, 'k14', '', NULL, 'Pumpkins, squash, zucchini and gourds', 11);
INSERT INTO production_systems VALUES (203, 'k15', '', NULL, 'Spinach', 11);
INSERT INTO production_systems VALUES (204, 'k16', '', NULL, 'Eggplant (aubergine, brinjal)', 11);
INSERT INTO production_systems VALUES (205, 'k17', '', NULL, 'Celery', 11);
INSERT INTO production_systems VALUES (206, 'k18', '', NULL, 'Capsicum (bell pepper)', 11);
INSERT INTO production_systems VALUES (207, 'l1', '', NULL, 'Plant products (general/other)', 12);
INSERT INTO production_systems VALUES (208, 'l2', '', NULL, 'Cocoa/cacao', 12);
INSERT INTO production_systems VALUES (209, 'l3', '', NULL, 'Coconuts', 12);
INSERT INTO production_systems VALUES (210, 'l4', '', NULL, 'Coffee', 12);
INSERT INTO production_systems VALUES (211, 'l5', '', NULL, 'Gums, rubber', 12);
INSERT INTO production_systems VALUES (212, 'l6', '', NULL, 'Hops', 12);
INSERT INTO production_systems VALUES (213, 'l7', '', NULL, 'Mat?(yerbas)', 12);
INSERT INTO production_systems VALUES (214, 'l8', '', NULL, 'Mushrooms and truffles', 12);
INSERT INTO production_systems VALUES (215, 'l9', '', NULL, 'Sugar cane', 12);
INSERT INTO production_systems VALUES (216, 'l10', '', NULL, 'Sugar crops, (general/other)', 12);
INSERT INTO production_systems VALUES (217, 'l11', '', NULL, 'Tea', 12);
INSERT INTO production_systems VALUES (218, 'l12', '', NULL, 'Tobacco, unmanufactured', 12);
INSERT INTO production_systems VALUES (219, 'I13', '', NULL, 'Stevia', 12);
INSERT INTO production_systems VALUES (220, 'l14', '', NULL, 'Cupuacu (related to cacao)', 12);
INSERT INTO production_systems VALUES (221, 'l15', '', NULL, 'Roselle', 12);
INSERT INTO production_systems VALUES (222, 'l16', '', NULL, 'Grasses', 12);
INSERT INTO production_systems VALUES (223, 'l17', '', NULL, 'Basil', 12);
INSERT INTO production_systems VALUES (224, 'm1', '', NULL, 'Cookstove', 13);
INSERT INTO production_systems VALUES (225, 'm2', '', NULL, 'Biodigestor', 13);
INSERT INTO production_systems VALUES (226, 'm3', '', NULL, 'Biomass feedstock', 13);
INSERT INTO production_systems VALUES (227, 'm4', 'Biodigestor byproducts like Slurry for fertilizer, etc. And related cobenefits for health, etc.', NULL, 'Biodigestor byproducts and cobenefits', 13);
INSERT INTO production_systems VALUES (228, 'm5', '', NULL, 'Biogas', 13);
INSERT INTO production_systems VALUES (229, 'm6', '', NULL, 'Conventional energy (coal for cooking)', 13);
INSERT INTO production_systems VALUES (230, 'm7', '', NULL, 'Conventional energy (coal for heating)', 13);
INSERT INTO production_systems VALUES (231, 'm8', '', NULL, 'Conventional cooking + heating energy (various or unspecified)', 13);
INSERT INTO production_systems VALUES (232, 'n1', '', NULL, 'Other', 14);
INSERT INTO production_systems VALUES (233, 'n2', '', NULL, 'Agroforestry system', 14);
INSERT INTO production_systems VALUES (234, 'n3', '', NULL, 'Harbacious legume', 14);
INSERT INTO production_systems VALUES (235, 'n4', '', NULL, 'Flowering plants (i.e tithonia)', 14);
INSERT INTO production_systems VALUES (236, 'n5', '', NULL, 'Fungal diversity', 14);
INSERT INTO production_systems VALUES (237, 'n6', '', NULL, 'Bacterial diversity', 14);
INSERT INTO production_systems VALUES (238, 'n7', '', NULL, 'Crotaliaria', 14);
INSERT INTO production_systems VALUES (239, 'n8', '', NULL, 'Aloe', 14);
INSERT INTO production_systems VALUES (240, 't1', '', NULL, 'Water harvesting structure', 14);
INSERT INTO production_systems VALUES (241, 't2', '', NULL, 'Irrigation technique/technology', 14);
INSERT INTO production_systems VALUES (242, 'u1', '', NULL, 'No relevant crop just soil experiment', 14);
INSERT INTO production_systems VALUES (243, 'o1', '', NULL, 'Forage grass', 15);
INSERT INTO production_systems VALUES (244, 'o2', '', NULL, 'Forage legume', 15);
INSERT INTO production_systems VALUES (245, 'o3', '', NULL, 'Lucerne', 15);
INSERT INTO production_systems VALUES (246, 'o4', '', NULL, 'Medicago (medic)', 15);
INSERT INTO production_systems VALUES (247, 'o5', '', NULL, 'Brachiaria', 15);
INSERT INTO production_systems VALUES (248, 'p1', '', NULL, 'Storage', 16);
INSERT INTO production_systems VALUES (249, 'p2', '', NULL, 'Crib', 16);
INSERT INTO production_systems VALUES (250, 'p3', '', NULL, 'Sack', 16);
INSERT INTO production_systems VALUES (251, 'p4', '', NULL, 'Mud silos', 16);
INSERT INTO production_systems VALUES (252, 'p5', '', NULL, 'Polyethylene bag', 16);
INSERT INTO production_systems VALUES (253, 'p6', 'Traditional, cylindrical structure with walls made of woven vegetable material in Benin', NULL, 'Ava', 16);
INSERT INTO production_systems VALUES (254, 'p7', '', NULL, 'Improved granary', 16);
INSERT INTO production_systems VALUES (255, 'p8', '', NULL, 'Traditional granary', 16);
INSERT INTO production_systems VALUES (256, 'q1', '', NULL, 'Maize straw/stover', 17);
INSERT INTO production_systems VALUES (257, 'q2', '', NULL, 'Rice residues', 17);
INSERT INTO production_systems VALUES (258, 'q3', '', NULL, 'Groundnut residues', 17);
INSERT INTO production_systems VALUES (259, 'q4', '', NULL, 'Sorgum residues', 17);
INSERT INTO production_systems VALUES (260, 'q5', '', NULL, 'soybean residues', 17);
INSERT INTO production_systems VALUES (261, 'r1', '', NULL, 'N-fixing', 18);
INSERT INTO production_systems VALUES (262, 'r2', '', NULL, 'Non N-fixing', 18);
INSERT INTO production_systems VALUES (263, 's1', '', NULL, 'Sunhemp', 19);
INSERT INTO production_systems VALUES (264, 's2', '', NULL, 'Sesbanias', 19);


