-- Practices and indicators data

INSERT INTO practice_themes (id, code, description, documentation, name) VALUES (1, '1', NULL, NULL, 'Agroforestry');
INSERT INTO practice_themes (id, code, description, documentation, name) VALUES (2, '2', NULL, NULL, 'Agronomy');        
INSERT INTO practice_themes (id, code, description, documentation, name) VALUES (3, '3', NULL, NULL, 'Food energy systems');             
INSERT INTO practice_themes (id, code, description, documentation, name) VALUES (4, '4', NULL, NULL, 'Livestock');       
INSERT INTO practice_themes (id, code, description, documentation, name) VALUES (5, '5', NULL, NULL, 'Post Harvest');    
INSERT INTO practice_themes (id, code, description, documentation, name) VALUES (6, '6', NULL, NULL, 'Non-priority CSA');
INSERT INTO practice_themes (id, code, description, documentation, name) VALUES (9, '9', NULL, NULL, 'Other');
INSERT INTO practice_themes (id, code, description, documentation, name) VALUES (10, '10', NULL, NULL, 'Non-CSA');         

INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (1, '1', NULL, NULL, 'Land restoration', 1);   
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (2, '2', NULL, NULL, 'Intercropping', 1);      
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (3, '3', NULL, NULL, 'Parklands', 1);          
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (4, '4', NULL, NULL, 'Boundary planting', 1);  
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (5, '5', NULL, NULL, 'Silvopasture', 1);       
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (6, '6', NULL, NULL, 'Multi-strata agroforestry', 1);          
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (7, '7', NULL, NULL, 'Combined treatment', 1); 
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (8, '8', NULL, NULL, 'Combined organic and inorganic Fertilization', 2);       
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (9, '9', NULL, NULL, 'Conservation Agriculture', 2);           
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (10, '10', NULL, NULL, 'Crop Rotations', 2);   
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (11, '11', NULL, NULL, 'Crop Tolerance to Stress', 2);         
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (12, '12', NULL, NULL, 'Crop Tolerance to Stress Part 2', 2);  
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (13, '13', NULL, NULL, 'Diversification', 2);  
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (14, '14', NULL, NULL, 'Green Manures/cover crop', 2);         
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (15, '15', NULL, NULL, 'Improved Rice Management', 2);         
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (16, '16', NULL, NULL, 'Inorganic inputs (NPK)', 2);           
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (17, '17', NULL, NULL, 'Input', 2);            
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (18, '18', NULL, NULL, 'Integrated nutrient management', 2);   
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (19, '19', NULL, NULL, 'Mulching', 2);         
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (20, '20', NULL, NULL, 'Organic (bioinput)', 2);               
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (21, '21', NULL, NULL, 'pH control', 2);       
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (22, '22', NULL, NULL, 'Restoration of degraded land', 2);     
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (23, '23', NULL, NULL, 'Small scale irrigation (farm/field)', 2);              
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (24, '24', NULL, NULL, 'Small scale irrigation Part 2', 2);    
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (25, '25', NULL, NULL, 'Tilling', 2);          
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (26, '26', NULL, NULL, 'Combined agronomy treatment', 2);      
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (27, '27', NULL, NULL, 'Organic inputs (other)', 2);           
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (28, '28', NULL, NULL, 'Crop Rotation', 2);    
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (29, '29', NULL, NULL, 'Fertilizer', 2);       
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (30, '30', NULL, NULL, 'relay cropping', 2);   
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (31, '31', NULL, NULL, 'crop rotation', 2);    
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (32, '32', NULL, NULL, 'Biogas from anaerobic-, bio- digesters', 3);           
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (33, '33', NULL, NULL, 'Improved cookstoves', 3);              
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (34, '34', NULL, NULL, 'Energy switching', 3); 
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (35, '35', NULL, NULL, 'Biofertilizer', 3);    
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (36, '36', NULL, NULL, 'Aquasilviculture', 4); 
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (37, '37', NULL, NULL, 'Diet management', 4);  
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (38, '38', NULL, NULL, 'Disease management', 4);               
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (39, '39', NULL, NULL, 'Genetic improvement', 4);              
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (40, '40', NULL, NULL, 'Improved pastures', 4);
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (41, '41', NULL, NULL, 'Manure management', 4);
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (42, '42', NULL, NULL, 'Rotational grazing', 4);               
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (43, '43', NULL, NULL, 'Harvesting technique', 5);             
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (44, '44', NULL, NULL, 'Improved on-farm storage', 5);         
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (45, '45', NULL, NULL, 'Non-priority CSA', 6); 
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (46, '46', NULL, NULL, 'Fertigation', 6);      
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (47, '47', NULL, NULL, 'Solar heating', 6);    
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (48, '48', NULL, NULL, 'other organic inputs', 6);             
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (49, '49', NULL, NULL, 'up and downslope cultivation', 6);     
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (50, '50', NULL, NULL, 'contour planting', 6); 
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (51, '51', NULL, NULL, 'hedging', 6);          
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (52, '52', NULL, NULL, 'fertilization', 6);    
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (53, '53', NULL, NULL, 'residual effect of an inputs (chemical or organic)', 6);               
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (54, '54', NULL, NULL, 'inputs', 6);           
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (55, '55', NULL, NULL, 'irrigation', 6);       
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (56, '56', NULL, NULL, 'other organic input', 6);              
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (57, '57', NULL, NULL, 'combined treatment', 6);               
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (58, '58', NULL, NULL, 'fertilization/irrigation', 6);         
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (59, '59', NULL, NULL, 'Combined CSA + Non-CSA', 9);           
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (60, '60', NULL, NULL, 'Specifiy - other practice not in this list', 9);       
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (62, '62', NULL, NULL, 'Non-CSA', 10);
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (63, '63', NULL, NULL, '(food energy)', 10);   
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (64, '64', NULL, NULL, '(post harvest)', 10);  
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (65, '65', NULL, NULL, 'water management', 10);
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (66, '66', NULL, NULL, 'soil management', 10); 
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (67, '67', NULL, NULL, 'agronomy', 10);        
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (68, '68', NULL, NULL, 'combined non CSA', 10);
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (69, '69', NULL, NULL, 'agroforestry', 10);    
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (70, '70', NULL, NULL, 'rice systems', 10);    
INSERT INTO practice_levels (id, code, description, documentation, name, theme_id) VALUES (71, '71', NULL, NULL, 'agronomy irrigation details', 10);

INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 1, 'a1', 'Systematic regrowth of tress or seeds on agricultural, forest or pasture land. It is used in areas where there are stumps that can coppice or seeds that can germinate', NULL, 'Farmer managed natural regeneration', '', 1);   
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 2, 'a2', '', NULL, 'Intercropping (agroforestry) in rows/alleys (both)', '', 2);          
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 3, 'a3', 'woody species in arranged in rows; agricultural species in alleys in between hedges; microzonal or strip arrangemnet; Interaction of woody perennials (fast growing, leguminous that coppice) and crops. OBS: sometimes referred to as hedgerow intercropping, not to confuse with hedgerow boundary planting!!', NULL, 'Intercropping (agroforestry) in rows/alleys (N-fix)', '', 2);          
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 4, 'a4', 'Intercropping with trees and shrubs (non-N-fix) and grass', NULL, 'Intercropping (agroforestry) in rows/alleys (non-N-fix)', '', 2);            
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 5, 'a5', 'trees/shrubs/grass strip scattered in the field', NULL, 'Intercropping (agroforestry) mix (both)', '', 2);   
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 6, 'a6', 'trees/shrubs/grass strip scattered in the field', NULL, 'Intercropping (agroforestry) mix (N-fix)', '', 2);     
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 7, 'a7', 'trees/shrubs/grass strip scattered in the field', NULL, 'Intercropping (agroforestry) mix (non-N-fix)', '', 2); 
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 8, 'a8', 'Intercropping under scattered or regularly planted trees "Scattered multipurpose trees occur on farmlands as a result of farmer selection and protection"', NULL, 'Parklands', '', 3);          
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 9, 'a9', 'Barriers of trees or shrubs that protect crops and forage against wind', NULL, 'windbreaks, shelterbelts', '', 4);              
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 10, 'a10', 'Live fence and hedges are planted in rows along the edge of the field to reduce the effect of wind or runoff on crops', NULL, 'Living fences / hedges / riparian buffer strip', '', 4);       
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 11, 'a11', 'Combination of trees or shrubs with forage (pasture grass) and livestock', NULL, 'Silvopasture', '', 5);      
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 12, 'a12', 'Several strata of trees occupied by tree crops (coffee, tea, cacao, banana etc) with shade trees include two or more vegetation layers and more than one tree species. Multistorey systems. Several strata of trees occupied by tree crops (coffee, tea, cacao, banana etc) with shade trees \\n- include two or more vegetation layers and more than one tree species \\n- multiple tree crop species and crops (N-fixing legume cover crops', NULL, 'Multi-strata agroforestry', '', 6);        
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 13, 'a13', '', NULL, '', '', 7);          
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 14, 'a14', 'for example, if no information on what kind of species (N-fix/non-N-fix etc) or the spacing', NULL, 'Intercropping (agroforestry) unspecified', '', 2);       
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 15, 'b1', 'Using a combination of both organic and inorganic inputs', NULL, '', '', 8);   
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 16, 'b2', 'Only includes all 3 practices: reduced til, crop rotation, and soil cover', NULL, 'Conservation Agriculture: reduce till, crop rotations, soil cover', '', 9); 
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 17, 'b3', 'Crop rotation - Crop combination', NULL, 'Crop rotation - Crop combination', '', 10);          
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 18, 'b4', 'Testing different crops and cultivars and their potential resistance to drought', NULL, 'seed bank', '', 11);  
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 19, 'b5', 'Testing different crops and cultivars and their potential resistance to heat', NULL, 'Heat tolerance', '', 11);
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 20, 'b6', 'Testing different crops and cultivars and their potential resistance to salt stress', NULL, 'Salinity Tolerance', '', 12);     
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 21, 'b7', 'Increase the number and kind of crops in the rotation in both space (field/farm? and in time (over the cropping cycle))', NULL, 'Increased diversity in rotation', '', 13);    
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 22, 'b8', 'Increasing the diversity in the types of crops grown in the field/farm. i.e. instead of just maize, they add sweet potato, yam, sorghum etc', NULL, 'Increased diversity of crops', '', 13);   
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 23, 'b9', 'Increasing the number of cultivars in field/farm. i.e. varieties of maize', NULL, 'Increased diversty of cultivars', '', 13);  
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 24, 'b10', 'Multiple crops in an area in a given time (also integration of livestock)', NULL, 'Polyculture system', '', 13);              
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 25, 'b11', 'Green manures of leguminous crops', NULL, 'Green Manure - Leguminous', '', 14);               
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 26, 'b12', 'Green manures of NON-leguminous crops', NULL, 'Green Manure - of non Leguminous', '', 14);    
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 27, 'b13', 'AWD is flooding and draining and flooding.', NULL, 'Alternate wetting and drying (AWD)', '', 15);             
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 28, 'b14', 'the field is drained midseason (not reflooded)', NULL, 'Mid-season drainage', '', 15);        
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 29, 'b15', 'A System package - includes early transpat (8-12 days), 25cm distance, alternate wet and dry', NULL, 'System of Rice Intensification (SRI)', '', 15);         
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 30, 'b16', 'Using N,P,K inorganic inputs on fields can test timing and amount', NULL, 'Inorganic inputs - K', '', 16);    
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 31, 'b17', 'Using N,P,K inorganic inputs on fields can test timing and amount', NULL, 'Inorganic inputs - N', '', 16);    
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 32, 'b18', 'Using N,P,K inorganic inputs on fields can test timing and amount', NULL, 'Inorganic inputs - N,K', '', 16);  
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 33, 'b19', 'Using N,P,K inorganic inputs on fields can test timing and amount', NULL, 'Inorganic inputs - N,P', '', 16);  
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 34, 'b20', 'Using N,P,K inorganic inputs on fields can test timing and amount', NULL, 'Inorganic inputs - N,P,K', '', 16);
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 35, 'b21', 'Using N,P,K inorganic inputs on fields can test timing and amount', NULL, 'Inorganic inputs - P', '', 16);    
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 36, 'b22', 'Using N,P,K inorganic inputs on fields can test timing and amount', NULL, 'Inorganic inputs - P, K', '', 16); 
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 37, 'b23', '', NULL, 'Urea', '', 17);     
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 38, 'b24', 'Discussed by the author as a whole', NULL, 'Integrate Nutrient Management discussed as a whole', '', 18);     
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 39, 'b25', 'Intercropping with leguminous crops', NULL, 'Intercropping (agronomy) with leguminous crops', '', 2);         
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 40, 'b26', 'Mulching with materials such as plastic', NULL, 'Mulching - External material (plastic)', '', 19);            
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 41, 'b27', 'Mulching with plant residues that are not explicitly green manure', NULL, 'Mulching - Plant residues that is not green manure', '', 19);      
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 42, 'b28', 'Application of biochar in the field', NULL, 'Biochar', '', 20);               
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 43, 'b29', 'Application of compost to the field', NULL, 'Compost', '', 20);               
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 44, 'b30', 'Application of manure to the field', NULL, 'Manure', '', 20); 
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 45, 'b31', 'a mixture of residues, manure, biochar, compost, (one or more applied at one time)', NULL, 'combined organic treatments/inputs', '', 20);     
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 46, 'b32', 'Application of lime/Ca on the field', NULL, 'Liming or Ca', '', 21);          
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 47, 'b33', 'Identified in paper by author - small pit in degraded land, filled with manure/compost/nutrients before rainy season to capture water and grow plants', NULL, 'Zai', '', 22); 
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 48, 'b34', 'The use of plastic pipes to drip water into the soil at low pressure', NULL, 'Drip irrigation', '', 23);      
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 49, 'b35', 'Collection and storage of water runoff for irrigation purposes', NULL, 'Water harvest/storage', '', 23);      
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 50, 'b36', 'Also called partial root zone drying PRD - part of the root is exposed to drying soil and the remaining is irrigated in accordance with crop requirements and soil drying rate', NULL, 'Alternate partial root zone irrigation', '', 24);     
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 51, 'b37', 'Application of water below full crop requirements', NULL, 'deficit irrigation', '', 24);      
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 52, 'b38', 'No-till as defined by author', NULL, 'No till/plough', '', 25);               
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 53, 'b39', 'Any tilling practice which aims to reduce soil disturbance', NULL, 'Reduced till/plough', '', 25);            
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 54, 'b40', '', NULL, 'Other combined agronomy practices (apart from organic and inorganic inputs)', '', 26);              
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 55, 'b41', 'The addition of crop residues (unspecified) e.g. prunings', NULL, 'Crop residue', '', 20);    
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 56, 'b42', '', NULL, 'Other organic inputs not on CSA list (e.g. vermicompost, urine, earthworms, ash)', '', 27);         
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 57, 'b43', '', NULL, 'Crop Rotation with Legume', '', 28);
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 58, 'b44', '', NULL, 'Other inorganic fertilizer (NOT NPK)', '', 29);     
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 59, 'b45', '', NULL, 'stone rows', '', 23);               
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 60, 'b46', '', NULL, 'grass strips', '', 23);             
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 61, 'b47', '', NULL, 'basins', '', 23);   
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 62, 'b48', '', NULL, 'double cropping/relay cropping', '', 30);           
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 63, 'b49', '', NULL, 'crop rotation (adding non-legumes in sequence)', '', 31);           
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 64, 'b50', '', NULL, 'intercropping non legume', '', 2);  
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 65, 'b51', '', NULL, 'Mulching - using gravel (not plant residues)', '', 19);             
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 66, 'b52', '', NULL, 'microcatchment', '', 23);           
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 67, 'c1', '', NULL, 'Biogas from anaerobic-, bio- digesters', '', 32);    
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 68, 'c2', '', NULL, 'Improved cookstove', '', 33);        
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 69, 'c3', '', NULL, 'Changing biomass feedstocks (for cookstoves or biodigestors only)', '', 34);         
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 70, 'c4', '', NULL, 'Biodigestor slurry (biofertilizer)', '', 35);        
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 71, 'd1', 'Aquaculture practise tha is combined with forest cultivation/activities', NULL, 'Aquasilviculture', '', 36);   
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 72, 'd2', '', NULL, 'Integrated multitrophic aquaculture', '', 36);       
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 73, 'd3', '', NULL, 'Improved feed acceptability, palatability and digestibility', '', 37);               
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 74, 'd4', '', NULL, 'Improved protein and energy intake', '', 37);        
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 75, 'd5', 'use of any feed ingredients that is not directly in use for human consumption', NULL, 'Non-conventional feeds', '', 37);       
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 76, 'd6', '', NULL, 'Biological control of vectors', '', 38);             
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 77, 'd7', '', NULL, 'Raising of resistance breeds', '', 38);              
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 78, 'd8', '', NULL, 'Assisted reproduction', '', 39);     
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 79, 'd9', '', NULL, 'Changing breeds', '', 39);           
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 80, 'd10', '', NULL, 'Hybridization', '', 39);            
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 81, 'd11', '', NULL, 'Forage legumes', '', 40);           
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 82, 'd12', '', NULL, 'Non-indigenous forage or fodder species', '', 40);  
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 83, 'd13', '', NULL, 'Manure collection', '', 41);        
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 84, 'd14', '', NULL, 'Manure storage', '', 41);           
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 85, 'd15', '', NULL, 'Manure treatment', '', 41);         
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 86, 'd16', '', NULL, 'Harvesting of high quality pasture', '', 42);       
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 87, 'd17', '', NULL, 'Improved supplement use', '', 42);  
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 88, 'd18', '', NULL, '', '', 7);          
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 89, 'f1', '', NULL, 'Alternate harvesting techniques', '', 43);           
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 90, 'f2', '', NULL, 'Harvesting time', '', 43);           
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 91, 'f3', '', NULL, 'Improved drying techniques', '', 44);
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 92, 'f4', '', NULL, 'Improved food/feed/seed/grain preservation technique', '', 44);      
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 93, 'f5', '', NULL, 'Improved physical storage', '', 44); 
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 94, 'g1', '', NULL, 'Non-priority CSA practice', '', 45); 
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 95, 'g2', '', NULL, '', '', 46);          
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 96, 'g3', '', NULL, '', '', 47);          
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 97, 'g4', '', NULL, 'urban solid waste, Household waste', '', 48);        
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 98, 'g5', '', NULL, 'industrial waste i.e. pulp mill waste, slaughterhouse waste, sugarcane waste', '', 48);              
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 99, 'g6', '', NULL, 'vermicompost', '', 48);              
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 100, 'g7', '', NULL, 'earthworms', '', 48);               
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 101, 'g8', '', NULL, 'coir pith (coconut husks)', '', 48);
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 102, 'g9', '', NULL, 'Other inorganic fertilizer (NOT NPK)', '', 29);     
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 103, 'g10', '', NULL, '', '', 49);        
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 104, 'g11', '', NULL, 'contour planting', '', 50);        
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 105, 'g12', '', NULL, 'hedging', '', 51); 
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 106, 'g13', '', NULL, 'subsoiling', '', 52);              
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 107, 'g14', '', NULL, 'broadcast application', '', 52);   
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 108, 'g15', '', NULL, '', '', 53);        
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 109, 'g16', '', NULL, 'banding/ band placed fertilizer', '', 54);         
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 110, 'g17', '', NULL, 'sub surface application', '', 54); 
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 111, 'g18', '', NULL, 'irrigation spacing', '', 55);      
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 112, 'g19', '', NULL, 'irrigation timing', '', 55);       
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 113, 'g20', '', NULL, 'irrigation amounts/quantity/volume', '', 55);      
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 114, 'g21', '', NULL, 'ash', '', 54);     
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 115, 'g22', '', NULL, '', '', 52);        
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 116, 'g23', '', NULL, 'basin irrigation', '', 55);        
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 117, 'g24', '', NULL, 'other organic inputs (specify - for very particular/unique treatments)', '', 48);  
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 118, 'g25', '', NULL, 'municipal soli waste compost', '', 56);            
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 119, 'g26', '', NULL, 'combined priority and non-priority CSA treatment', '', 57);        
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 120, 'g27', '', NULL, 'timing', '', 52);  
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 121, 'g28', '', NULL, 'anthill', '', 48); 
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 122, 'g29', '', NULL, 'saline irrigation', '', 55);       
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 123, 'g30', '', NULL, 'amount', '', 52);  
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 124, 'g31', '', NULL, 'micronutrient', '', 52);           
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 125, 'g32', '', NULL, 'microdosing', '', 58);             
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 126, 'i1', '', NULL, '', '', 59);         
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 127, 'i2', '', NULL, '', '', 60);         
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 128, 'h1', '', NULL, 'Non-CSA practice', '', 60);         
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 129, 'h2', '', NULL, 'monoculture, sole crop', '', 62);   
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 130, 'h3', '', NULL, 'forest', '', 62);   
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 131, 'h4', '', NULL, 'shrubland', '', 62);
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 132, 'h5', '', NULL, 'unimproved species/practice', '', 62);              
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 133, 'h6', 'same as h26?', NULL, 'Conventional ploughing/tilling', '', 62);               
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 134, 'h7', '', NULL, 'full irrigation', '', 62);          
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 135, 'h8', '(similar to h41, rainfed)', NULL, 'No irrigation', '', 62);   
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 136, 'h9', '(similar to h32)', NULL, 'No fertilization', '', 62);         
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 137, 'h10', '', NULL, 'Conventional input use', '', 62);  
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 138, 'h11', '', NULL, 'Synthetic herbicide', '', 62);     
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 139, 'h12', '', NULL, 'Synthetic pesticide', '', 62);     
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 140, 'h13', '', NULL, 'Synthetic insecticide', '', 62);   
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 141, 'h14', '', NULL, 'traditional/unimproved/conventional stove technology', '', 63);    
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 142, 'h15', '', NULL, 'conventional biomass feedstocks', '', 63);         
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 143, 'h16', '', NULL, 'predominant biodigestor model', '', 63);           
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 144, 'h17', '', NULL, 'bare soil/no cover/residue removed/no mulch', '', 64);             
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 145, 'h18', '', NULL, 'conventional intercrop', '', 62);  
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 146, 'h19', '', NULL, 'irrigation (unspecified)', '', 62);
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 147, 'h20', '', NULL, 'indigenous storage structure', '', 64);            
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 148, 'h21', '', NULL, 'traditional/unimproved storage structure', '', 64);
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 149, 'h22', 'Paired most closely with CSA practice f4 - improved preservation technique', NULL, 'traditional/unimproved food/ feed/ seed preservation technique', '', 64);
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 150, 'h23', '(see more details in other rows before you use this)', NULL, 'Irrigation (other)', '', 65);  
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 151, 'h24', '', NULL, 'fallow', '', 62);  
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 152, 'h25', '', NULL, 'furrow irrigation', '', 65);       
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 153, 'h26', '', NULL, 'conventional energy sources', '', 63);             
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 154, 'h27', 'same as h5', NULL, 'conventional/traditional ag practice (tillage, residue mgt, fertilization etc)', '', 66);
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 155, 'h28', 'same as h35', NULL, 'No Residues added or left, no mulching', '', 67);       
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 156, 'h29', '', NULL, 'No crop rotations', '', 67);       
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 157, 'h30', '', NULL, 'traditional/unimproved drying technique', '', 64); 
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 158, 'h31', '', NULL, 'Combined non-CSA treatment', '', 68);              
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 159, 'h32', '', NULL, 'No inputs or amendements or mulch', '', 67);       
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 160, 'h33', '', NULL, 'pasture/grassland', '', 69);       
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 161, 'h34', '', NULL, 'traditional/conventional agroforests', '', 69);    
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 162, 'h35', '', NULL, 'Residue removed', '', 67);         
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 163, 'h36', '', NULL, 'burning of plot or residue', '', 67);              
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 164, 'h37', '', NULL, 'field with only trees/tree plantation', '', 69);   
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 165, 'h38', '', NULL, 'no rotation/continuous cropping', '', 67);         
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 166, 'h39', '', NULL, 'seed inputs without special tolerance', '', 67);   
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 167, 'h40', '', NULL, 'farmer practice irrigation', '', 67);              
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 168, 'h41', '', NULL, 'rainfed', '', 67); 
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 169, 'h42', '', NULL, 'ground cover rice production system (GCRPS)', '', 67);             
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 170, 'h43', '', NULL, 'no stress conditions', '', 62);    
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 171, 'h44', '', NULL, 'other inputs', '', 62);            
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 172, 'h45', '', NULL, 'uncultivated soil', '', 67);       
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 173, 'h46', '', NULL, 'sprinkler irrigation', '', 67);    
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 174, 'h47', '', NULL, 'unimproved water harvest/storage structure', '', 67);              
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 175, 'h48', '', NULL, 'recommended managament practices of Rice', '', 70);
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 176, 'h50', '', NULL, 'conventional crop rotation', '', 67);              
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 177, 'h51', '', NULL, 'subsurface application (irrigation)', '', 71);     
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 178, 'h52', '', NULL, 'surface application (irrigation)', '', 71);        
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 179, 'h53', '', NULL, 'no water harvest/storage structure', '', 67);      
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 180, 'h54', '', NULL, 'full capacity irrigation', '', 67);
INSERT INTO practices (from_compendium, id, code, description, documentation, name, tags, level_id) VALUES (1, 181, 'h55', '', NULL, 'traditional cultivar choice', '', 67);

INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 1, '101.0', NULL, NULL, 'Grain or product yield per land unit', 'Yield');      
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 2, '102.0', NULL, NULL, 'Biomass yield per land unit', 'Yield');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 3, '103.0', NULL, NULL, 'Dry matter yield per land unit', 'Yield');            
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 4, '104.0', NULL, NULL, 'Thousand-kernel weight', 'Yield');    
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 5, '105.0', NULL, NULL, 'Residues per land unit', 'Yield');    
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 6, '106.0', NULL, NULL, 'Grain yield per unit labor', 'Yield');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 7, '107.0', NULL, NULL, 'Biomass yield per unit labor', 'Yield');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 8, '108.0', NULL, NULL, 'Thousand-kernel weight per unit labor', 'Yield');     
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 9, '109.0', NULL, NULL, 'Residue yield per unit labor', 'Yield');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 10, '110.0', NULL, NULL, 'Thousand-kernel weight', 'Yield');   
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 11, '111.0', NULL, NULL, 'Fresh root,tuber yield/area', 'Yield');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 12, '112.0', NULL, NULL, 'Bulb yield', 'Yield');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 13, '113.0', NULL, NULL, 'Grain yield per person/farm/household', 'Yield');    
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 14, '114.0', NULL, NULL, 'Biomass yield per person/household', 'Yield');       
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 15, '115.0', NULL, NULL, 'Thousand kernel weight per person/farm/household', 'Yield');         
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 16, '116.0', NULL, NULL, 'Residues per person/farm/household', 'Yield');       
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 17, '117.0', NULL, NULL, 'Calving Rate Experimental Animal', 'Yield');         
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 18, '118.0', NULL, NULL, 'Weight Gain Experimental Animal', 'Yield');          
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 19, '119.0', NULL, NULL, 'Food Product Experimental Animal', 'Yield');         
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 20, '120.0', NULL, NULL, 'Gross income per land unit', 'Income');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 21, '121.0', NULL, NULL, 'Gross income per unit labor', 'Income');             
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 22, '122.0', NULL, NULL, 'Gross income per household', 'Income');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 23, '123.0', NULL, NULL, 'Gross income per experimental animal', 'Income');    
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 24, '124.0', NULL, NULL, 'Net income per land unit', 'Income');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 25, '125.0', NULL, NULL, 'Net income per unit labor', 'Income');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 26, '126.0', NULL, NULL, 'Net returns per household', 'Income');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 27, '127.0', NULL, NULL, 'Net value per experimental Animal', 'Income');       
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 28, '128.0', NULL, NULL, 'Reduced household energy costs (monetary or in-kind)', 'Income');    
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 29, '129.0', NULL, NULL, 'Carbon credit revenues', 'Income');  
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 30, '130.0', NULL, NULL, 'Net present value (NPV)', 'Income'); 
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 31, '131.0', NULL, NULL, 'Payback period', 'Income');          
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 32, '132.0', NULL, NULL, 'Person-hours of labor', 'Labour');   
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 33, '133.0', NULL, NULL, 'Monetary value of labor', 'Labour'); 
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 34, '134.0', NULL, NULL, 'Thousand grain weight per land unit', 'Yield');      
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 35, '135.0', NULL, NULL, 'Straw yield per land unit', 'Yield');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 36, '136.0', NULL, NULL, 'Net income per unit output', 'Income');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 37, '137.0', NULL, NULL, 'Internal rate of return (IRR)', 'Income');           
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 38, '138.0', NULL, NULL, 'Reduced Household Expenditures on Fertilizer and/or Pesticides (savings)\\nReduced Household expenditures on firewood/fuel', 'Income'); 
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 39, '139.0', NULL, NULL, 'Net return per unit output', 'Income');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 40, '140.0', NULL, NULL, 'Net returns per farm', 'Income');    
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 41, '141.0', NULL, NULL, 'Net returns per digestor', 'Income');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 42, '142.0', NULL, NULL, 'Net returns per storage structure', 'Income');       
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 43, '143.0', NULL, NULL, 'Gross income per farm', 'Income');   
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 44, '144.0', NULL, NULL, 'Gross income per digestor', 'Income');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 45, '145.0', NULL, NULL, 'Gross income per storage structure', 'Income');      
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 46, '146.0', NULL, NULL, 'net return per land unit', 'Income');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 47, '147.0', NULL, NULL, 'Grain or product yield per tree, crop etc', 'Yield');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 48, '148.0', NULL, NULL, 'Biomass yield per plant, crop,', 'Yield');           
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 49, '149.0', NULL, NULL, 'Gross value of energy produced', 'Income');          
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 50, '150.0', NULL, NULL, 'Production cost per land unit', 'Income');           
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 51, '151.0', NULL, NULL, 'Net income per household', 'Income');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 52, '152.0', NULL, NULL, 'Net income per farm', 'Income');     
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 53, '153.0', NULL, NULL, 'Net income per digestor', 'Income'); 
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 54, '154.0', NULL, NULL, 'Net income per storage structure', 'Income');        
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 55, '155.0', NULL, NULL, 'Net income per land unit', 'Income');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 56, '156.0', NULL, NULL, 'Gross margin per land unit', 'Income');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 57, '157.0', NULL, NULL, 'Gross margin per unit labor', 'Income');             
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 58, '158.0', NULL, NULL, 'Gross margin per household', 'Income');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 59, '159.0', NULL, NULL, 'Gross margin per experimental animal', 'Income');    
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 60, '160.0', NULL, NULL, 'Gross margin per farm', 'Income');   
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 61, '161.0', NULL, NULL, 'Gross margin per digestor', 'Income');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 62, '162.0', NULL, NULL, 'Gross margin per storage structure', 'Income');      
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 63, '163.0', NULL, NULL, 'Household expenditure on fertilizer', 'Income');     
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 64, '164.0', NULL, NULL, 'Gross household expenditure on energy', 'Income');   
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 65, '165.0', NULL, NULL, 'Net household expenditures on energy', 'Income');    
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 66, '167.0', NULL, NULL, 'marketable harvest/yield per hectare', 'Yield');     
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 67, '168.0', NULL, NULL, 'Reduction in cost of production', 'Income');         
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 68, '169.0', NULL, NULL, 'Δ grain yield dry weight', 'Yield');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 69, '170.0', NULL, NULL, 'Dry matter yield per plant, crop,', 'Yield');        
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 70, '171.0', NULL, NULL, 'stover yield per land unit', 'Yield');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 71, '172.0', NULL, NULL, 'Gross income', 'Income');            
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 72, '173.0', NULL, NULL, 'Net income', 'Income');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 73, '174.0', NULL, NULL, 'Experimental animal reproduced', 'Yield');           
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 74, '175.0', NULL, NULL, 'Δ net income per farm', 'Income');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 75, '200.0', NULL, NULL, 'Per capita food consumption', 'Δ food access');   
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 76, '201.0', NULL, NULL, 'Depth of the food deficit', 'Δ food access');     
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 77, '202.0', NULL, NULL, 'Share of food expenditure (household scale)', 'Δ food access');   
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 78, '203.0', NULL, NULL, 'Species Richness (Species N)', 'Ecosystem services (biodiversity)'); 
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 79, '204.0', NULL, NULL, 'Shannon Index (H'')', 'Ecosystem services (biodiversity)');          
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 80, '205.0', NULL, NULL, 'Simpson Index', 'Ecosystem services (biodiversity)');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 81, '206.0', NULL, NULL, 'Alpha diversity', 'Ecosystem services (biodiversity)');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 82, '207.0', NULL, NULL, 'Beta diversity', 'Ecosystem services (biodiversity)');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 83, '208.0', NULL, NULL, 'Gamma diversity', 'Ecosystem services (biodiversity)');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 84, '209.0', NULL, NULL, 'Loss due to pests & pathogens (Livestock & Post-harvest only)', 'Pests and Pathogens');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 85, '210.0', NULL, NULL, 'Loss due to pests & pathogens (Livestock & Post-harvest only)', 'Pests and Pathogens');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 86, '211.0', NULL, NULL, 'Loss due to pests & pathogens (Livestock & Post-harvest only)', 'Pests and Pathogens');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 87, '212.0', NULL, NULL, 'Loss due to pests & pathogens (Livestock & Post-harvest only)', 'Pests and Pathogens');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 88, '213.0', NULL, NULL, 'Loss due to pests & pathogens (Livestock & Post-harvest only)', 'Pests and Pathogens');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 89, '214.0', NULL, NULL, 'Loss due to pests & pathogens (Livestock & Post-harvest only)', 'Pests and Pathogens');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 90, '215.0', NULL, NULL, 'Loss due to pests & pathogens (Livestock & Post-harvest only)', 'Pests and Pathogens');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 91, '216.0', NULL, NULL, 'Resistance / tolerance to pests & pathogens (Livestock & Post-harvest only)', 'Pests and Pathogens');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 92, '217.0', NULL, NULL, 'Wind Erosion', 'Soil Erosion/soil loss');            
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 93, '223.0', NULL, NULL, 'Soil organic matter (SOM)', 'Soil Quality');         
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 94, '224.0', NULL, NULL, 'Soil organic carbon (SOC)', 'Soil Quality');         
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 95, '225.0', NULL, NULL, 'Microbial biomass carbon', 'Soil Quality');          
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 96, '226.0', NULL, NULL, 'Soil N', 'Soil Quality');            
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 97, '227.0', NULL, NULL, 'Soil pH', 'Soil Quality');           
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 98, '228.0', NULL, NULL, 'Cation exchange capactity', 'Soil Quality');         
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 99, '229.0', NULL, NULL, 'Soil water holding capacity', 'Soil Quality');       
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 100, '230.0', NULL, NULL, 'Soil water balance', 'Soil Quality');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 101, '231.0', NULL, NULL, 'Soil water content (soil moisture)', 'Soil Quality');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 102, '232.0', NULL, NULL, 'WUE', 'Water Use Efficiency');      
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 103, '233.0', NULL, NULL, 'NUE (N)', 'Nutrient Use Efficiency');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 104, '234.0', NULL, NULL, 'NUE (P)', 'Nutrient Use Efficiency');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 105, '235.0', NULL, NULL, 'NUE (K)', 'Nutrient Use Efficiency');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 106, '236.0', NULL, NULL, 'Energy output/input ratio', 'Energy use Efficiency');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 107, '237.0', NULL, NULL, 'Thermal efficiency', 'Energy use Efficiency');      
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 108, '238.0', NULL, NULL, 'Emergy output/input ratio', 'Energy use Efficiency');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 109, '239.0', NULL, NULL, 'Female labour (in BARRIERS too)', 'Δ gendered impacts');         
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 110, '240.0', NULL, NULL, 'Male labour', 'Δ gendered impacts');             
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 111, '241.0', NULL, NULL, 'Difference of labour between female and male', 'Δ gendered impacts');            
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 112, '242.0', NULL, NULL, 'Female income', 'Δ gendered impacts');           
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 113, '243.0', NULL, NULL, 'Male income', 'Δ gendered impacts');             
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 114, '244.0', NULL, NULL, 'Difference of income between female and male', 'Δ gendered impacts');            
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 115, '245.0', NULL, NULL, 'Social capital related capacity: social network, access to information (in BARRIERS too)', 'Δ gendered impacts / adaptive capacity');            
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 116, '246.0', NULL, NULL, 'Financial capital related capacity: Labour and income will indicate financial adaptive capacity of women (in BARRIERS too)', 'Δ gendered impacts / adaptive capacity');          
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 117, '247.0', NULL, NULL, 'Human capital related capacity: Technology, health, education, information, skills, management capabilities (in BARRIERS too)', 'Δ gendered impacts / adaptive capacity');       
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 118, '248.0', NULL, NULL, 'Natural capital related capacity: access to assets (in BARRIERS too)', 'Δ gendered impacts / adaptive capacity');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 119, '249.0', NULL, NULL, 'Physical capital related capacity: access to new farming technologies (in BARRIERS too)', 'Δ gendered impacts / adaptive capacity');             
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 120, '250.0', NULL, NULL, 'Overall adaptive capacity', 'Δ gendered impacts / adaptive capacity');           
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 121, '251.0', NULL, NULL, 'Other 1', 'Δ gendered impacts / adaptive capacity');             
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 122, '252.0', NULL, NULL, 'Other 2', 'Δ gendered impacts / adaptive capacity');             
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 123, '253.0', NULL, NULL, 'Other 3', 'Δ gendered impacts / adaptive capacity');             
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 124, '254.0', NULL, NULL, 'Berger-Parker index', 'Ecosystem services (biodiversity)');         
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 125, '255.0', NULL, NULL, 'Total Soil carbon (Total Soil C)', 'Soil Quality'); 
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 126, '256.0', NULL, NULL, 'Pests and Pathogens', 'Pests and Pathogens');       
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 127, '257.0', NULL, NULL, 'NUE (NPK)', 'Nutrient Use Efficiency');             
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 128, '258.0', NULL, NULL, 'NUE (NPK) (Grain)', 'Nutrient Use Efficiency');     
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 129, '259.0', NULL, NULL, 'NUE (NPK) (total above round biomass)', 'Nutrient Use Efficiency'); 
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 130, '260.0', NULL, NULL, 'Net energy return (Energy out/energy in)', 'Energy use Efficiency');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 131, '261.0', NULL, NULL, 'System energy use efficiency', 'Energy use Efficiency');            
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 132, '262.0', NULL, NULL, 'Δ Soil pH', 'Δ Soil Quality');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 133, '263.0', NULL, NULL, 'Δ SOC', 'Δ Soil Quality');    
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 134, '264.0', NULL, NULL, 'Δ TOTAL N', 'Δ Soil Quality');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 135, '300.0', NULL, NULL, 'carbon dioxide equivalent emissions', 'Δ off farm emissions CO2 Eq');            
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 136, '301.0', NULL, NULL, 'methane emissions', 'Δ off farm emissions CO2 Eq');              
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 137, '302.0', NULL, NULL, 'nitrous oxide emissions', 'Δ off farm emissions CO2 Eq');        
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 138, '303.0', NULL, NULL, 'carbon dioxide emissions', 'Δ off farm emissions CO2 Eq');       
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 139, '304.0', NULL, NULL, 'carbon dioxide equivalent emissions', 'Δ on farm emissions CO2 Eq');             
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 140, '305.0', NULL, NULL, 'methane emissions', 'Δ on farm emissions CO2 Eq');               
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 141, '306.0', NULL, NULL, 'nitrous oxide emissions', 'Δ on farm emissions CO2 Eq');         
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 142, '307.0', NULL, NULL, 'carbon dioxide emissions', 'Δ on farm emissions CO2 Eq');        
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 143, '308.0', NULL, NULL, 'Soil organic carbon (SOC) stocks', 'Δ on farm stock CO2 Eq');    
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 144, '309.0', NULL, NULL, 'Plant biomass (aboveground)', 'Δ on farm stock CO2 Eq');         
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 145, '310.0', NULL, NULL, 'Plant biomass (belowground)', 'Δ on farm stock CO2 Eq');         
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 146, '311.0', NULL, NULL, 'Emissions (CO2 eq) per unit of output', 'Δ emissions intensity');
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 147, '312.0', NULL, NULL, 'avoided methane emissions', 'Δ gross avoided emissions');        
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 148, '313.0', NULL, NULL, 'avoided nitrous oxide emissions', 'Δ gross avoided emissions');  
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 149, '314.0', NULL, NULL, 'avoided carbon dioxide emissions', 'Δ gross avoided emissions'); 
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 150, '315.0', NULL, NULL, 'avoided carbon dioxide equivalent emissions', 'Δ gross avoided emissions');      
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 151, '316.0', NULL, NULL, 'avoided methane emissions', 'Δ net avoided emissions');          
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 152, '317.0', NULL, NULL, 'avoided nitrous oxide emissions', 'Δ net avoided emissions');    
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 153, '318.0', NULL, NULL, 'avoided carbon dioxide emissions', 'Δ net avoided emissions');   
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 154, '319.0', NULL, NULL, 'avoided carbon dioxide equivalent emissions', 'Δ net avoided emissions');        
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 155, '320.0', NULL, NULL, 'avoided woody biomass consumption', 'Δ reduced fuel wood consumption');          
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 156, '321.0', NULL, NULL, 'Δ on-farm CH4 uptake', 'Δ on farm sequestration CO2 Eq');     
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 157, '322.0', NULL, NULL, 'Δ total soil carbon (organic + inorganic) stocks', 'Δ on farm stock CO2 Eq'); 
INSERT INTO indicators (from_compendium, id, code, description, documentation, name, category) VALUES (1, 158, '323.0', NULL, NULL, 'woody biomass consumption', 'fuel wood consumption');               
